"""Stub Agent for system integration testing.

This module provides a dummy implementation of the BaseAgent interface.
It is used to verify that the Controller can correctly load an agent,
execute it, and retrieve results, without relying on external AI services.
"""

from typing import List, Any
from src.core.interfaces import BaseAgent
from src.schemas.common import AgentPayload, ReviewIssue, Category, Severity
from src.utils.logger import get_logger

logger = get_logger(__name__)


class StubAgent(BaseAgent):
    """A dummy agent that always returns a fixed set of issues.

    Used primarily for verifying the Controller <-> Judge wiring during
    initial development phases (Sprint 0.8).
    """

    def run(self, payload: AgentPayload) -> List[ReviewIssue]:
        """Executes the stub analysis.

        Args:
            payload (AgentPayload): The input payload (ignored by this stub).

        Returns:
            List[ReviewIssue]: A list containing a single hardcoded issue.
        """
        logger.info("Stub Agent is analyzing...")

        # Return a fake "High Severity" issue for testing purposes
        return [
            ReviewIssue(
                id="stub_001",
                file_path=payload.target_files[0].file_path
                if payload.target_files
                else "unknown",
                line_start=1,
                line_end=1,
                category=Category.BEST_PRACTICE,
                severity=Severity.HIGH,
                title="Stub Issue Detected",
                body="This is a test issue generated by the Sprint 0.8 Stub Agent.",
                suggestion="If you see this, the runtime engine is working.",
                rationale="System Integration Test",
                policy_violated="sys.test_protocol",
            )
        ]

    def get_tools(self) -> List[Any]:
        """Retrieves the list of tools available to this agent.

        Returns:
            List[Any]: Always returns an empty list for the Stub Agent.
        """
        return []